//
//  NSString+Emoji.m
//  EmojiToString
//
//  Created by Zhuochenming on 16/6/15.
//  Copyright © 2016年 Zhuochenming. All rights reserved.
//

#import "NSString+Emoji.h"

static NSDictionary *emojiAndUnicodeDic = nil;
static NSDictionary *unicodeAndEmojiDic = nil;

@implementation NSString (Emoji)

+ (void)getEmojiAndStringDic {
    @synchronized(self) {
        emojiAndUnicodeDic = @{
                              @"😄": @":smile:",
                              @"😆": @[@":laughing:", @":D"],
                              @"😊": @":blush:",
                              @"😃": @[@":smiley:", @":)", @":-)"],
                              @"☺": @":relaxed:",
                              @"😏": @":smirk:",
                              @"😞": @[@":disappointed:", @":("],
                              @"😍": @":heart_eyes:",
                              @"😘": @":kissing_heart:",
                              @"😚": @":kissing_closed_eyes:",
                              @"😳": @":flushed:",
                              @"😥": @":relieved:",
                              @"😌": @":satisfied:",
                              @"😁": @":grin:",
                              @"😉": @[@":wink:", @";)", @";-)"],
                              @"😜": @[@":wink2:", @":P"],
                              @"😝": @":stuck_out_tongue_closed_eyes:",
                              @"😀": @":grinning:",
                              @"😗": @":kissing:",
                              @"😙": @":kissing_smiling_eyes:",
                              @"😛": @":stuck_out_tongue:",
                              @"😴": @":sleeping:",
                              @"😟": @":worried:",
                              @"😦": @":frowning:",
                              @"😧": @":anguished:",
                              @"😮": @[@":open_mouth:", @":o"],
                              @"😬": @":grimacing:",
                              @"😕": @":confused:",
                              @"😯": @":hushed:",
                              @"😑": @":expressionless:",
                              @"😒": @":unamused:",
                              @"😅": @":sweat_smile:",
                              @"😓": @":sweat:",
                              @"😩": @":weary:",
                              @"😔": @":pensive:",
                              @"😞": @":dissapointed:",
                              @"😖": @":confounded:",
                              @"😨": @":fearful:",
                              @"😰": @":cold_sweat:",
                              @"😣": @":persevere:",
                              @"😢": @":cry:",
                              @"😭": @":sob:",
                              @"😂": @":joy:",
                              @"😲": @":astonished:",
                              @"😱": @":scream:",
                              @"😫": @":tired_face:",
                              @"😠": @":angry:",
                              @"😡": @":rage:",
                              @"😤": @":triumph:",
                              @"😪": @":sleepy:",
                              @"😋": @":yum:",
                              @"😷": @":mask:",
                              @"😎": @":sunglasses:",
                              @"😵": @":dizzy_face:",
                              @"👿": @":imp:",
                              @"😈": @":smiling_imp:",
                              @"😐": @":neutral_face:",
                              @"😶": @":no_mouth:",
                              @"😇": @":innocent:",
                              @"👽": @":alien:",
                              @"💛": @":yellow_heart:",
                              @"💙": @":blue_heart:",
                              @"💜": @":purple_heart:",
                              @"❤": @":heart:",
                              @"💚": @":green_heart:",
                              @"💔": @":broken_heart:",
                              @"💓": @":heartbeat:",
                              @"💗": @":heartpulse:",
                              @"💕": @":two_hearts:",
                              @"💞": @":revolving_hearts:",
                              @"💘": @":cupid:",
                              @"💖": @":sparkling_heart:",
                              @"✨": @":sparkles:",
                              @"⭐️": @":star:",
                              @"🌟": @":star2:",
                              @"💫": @":dizzy:",
                              @"💥": @":boom:",
                              @"💢": @":anger:",
                              @"❗": @":exclamation:",
                              @"❓": @":question:",
                              @"❕": @":grey_exclamation:",
                              @"❔": @":grey_question:",
                              @"💤": @":zzz:",
                              @"💨": @":dash:",
                              @"💦": @":sweat_drops:",
                              @"🎶": @":notes:",
                              @"🎵": @":musical_note:",
                              @"🔥": @":fire:",
                              @"💩": @[@":poop:", @":hankey:", @":shit:"],
                              @"👍": @[@":+1:", @":thumbsup:"],
                              @"👎": @[@":-1:", @":thumbsdown:"],
                              @"👌": @":ok_hand:",
                              @"👊": @":punch:",
                              @"✊": @":fist:",
                              @"✌": @":v:",
                              @"👋": @":wave:",
                              @"✋": @":hand:",
                              @"👐": @":open_hands:",
                              @"☝": @":point_up:",
                              @"👇": @":point_down:",
                              @"👈": @":point_left:",
                              @"👉": @":point_right:",
                              @"🙌": @":raised_hands:",
                              @"🙏": @":pray:",
                              @"👆": @":point_up_2:",
                              @"👏": @":clap:",
                              @"💪": @":muscle:",
                              @"🚶": @":walking:",
                              @"🏃": @":runner:",
                              @"👫": @":couple:",
                              @"👪": @":family:",
                              @"👬": @":two_men_holding_hands:",
                              @"👭": @":two_women_holding_hands:",
                              @"💃": @":dancer:",
                              @"👯": @":dancers:",
                              @"🙆": @":ok_woman:",
                              @"🙅": @":no_good:",
                              @"💁": @":information_desk_person:",
                              @"🙋": @":raised_hand:",
                              @"👰": @":bride_with_veil:",
                              @"🙎": @":person_with_pouting_face:",
                              @"🙍": @":person_frowning:",
                              @"🙇": @":bow:",
                              @"💏": @":couplekiss:",
                              @"💑": @":couple_with_heart:",
                              @"💆": @":massage:",
                              @"💇": @":haircut:",
                              @"💅": @":nail_care:",
                              @"👦": @":boy:",
                              @"👧": @":girl:",
                              @"👩": @":woman:",
                              @"👨": @":man:",
                              @"👶": @":baby:",
                              @"👵": @":older_woman:",
                              @"👴": @":older_man:",
                              @"👱": @":person_with_blond_hair:",
                              @"👲": @":man_with_gua_pi_mao:",
                              @"👳": @":man_with_turban:",
                              @"👷": @":construction_worker:",
                              @"👮": @":cop:",
                              @"👼": @":angel:",
                              @"👸": @":princess:",
                              @"😺": @":smiley_cat:",
                              @"😸": @":smile_cat:",
                              @"😻": @":heart_eyes_cat:",
                              @"😽": @":kissing_cat:",
                              @"😼": @":smirk_cat:",
                              @"🙀": @":scream_cat:",
                              @"😿": @":crying_cat_face:",
                              @"😹": @":joy_cat:",
                              @"😾": @":pouting_cat:",
                              @"👹": @":japanese_ogre:",
                              @"👺": @":japanese_goblin:",
                              @"🙈": @":see_no_evil:",
                              @"🙉": @":hear_no_evil:",
                              @"🙊": @":speak_no_evil:",
                              @"💂": @":guardsman:",
                              @"💀": @":skull:",
                              @"👣": @":feet:",
                              @"👄": @":lips:",
                              @"💋": @":kiss:",
                              @"💧": @":droplet:",
                              @"👂": @":ear:",
                              @"👀": @":eyes:",
                              @"👃": @":nose:",
                              @"👅": @":tongue:",
                              @"💌": @":love_letter:",
                              @"👤": @":bust_in_silhouette:",
                              @"👥": @":busts_in_silhouette:",
                              @"💬": @":speech_balloon:",
                              @"💭": @":thought_balloon:",
                              @"☀": @":sunny:",
                              @"☔": @":umbrella:",
                              @"☁": @":cloud:",
                              @"❄": @":snowflake:",
                              @"⛄": @":snowman:",
                              @"⚡": @":zap:",
                              @"🌀": @":cyclone:",
                              @"🌁": @":foggy:",
                              @"🌊": @":ocean:",
                              @"🐱": @":cat:",
                              @"🐶": @":dog:",
                              @"🐭": @":mouse:",
                              @"🐹": @":hamster:",
                              @"🐰": @":rabbit:",
                              @"🐺": @":wolf:",
                              @"🐸": @":frog:",
                              @"🐯": @":tiger:",
                              @"🐨": @":koala:",
                              @"🐻": @":bear:",
                              @"🐷": @":pig:",
                              @"🐽": @":pig_nose:",
                              @"🐮": @":cow:",
                              @"🐗": @":boar:",
                              @"🐵": @":monkey_face:",
                              @"🐒": @":monkey:",
                              @"🐴": @":horse:",
                              @"🐎": @":racehorse:",
                              @"🐫": @":camel:",
                              @"🐑": @":sheep:",
                              @"🐘": @":elephant:",
                              @"🐼": @":panda_face:",
                              @"🐍": @":snake:",
                              @"🐦": @":bird:",
                              @"🐤": @":baby_chick:",
                              @"🐥": @":hatched_chick:",
                              @"🐣": @":hatching_chick:",
                              @"🐔": @":chicken:",
                              @"🐧": @":penguin:",
                              @"🐢": @":turtle:",
                              @"🐛": @":bug:",
                              @"🐝": @":honeybee:",
                              @"🐜": @":ant:",
                              @"🐞": @":beetle:",
                              @"🐌": @":snail:",
                              @"🐙": @":octopus:",
                              @"🐠": @":tropical_fish:",
                              @"🐟": @":fish:",
                              @"🐳": @":whale:",
                              @"🐋": @":whale2:",
                              @"🐬": @":dolphin:",
                              @"🐄": @":cow2:",
                              @"🐏": @":ram:",
                              @"🐀": @":rat:",
                              @"🐃": @":water_buffalo:",
                              @"🐅": @":tiger2:",
                              @"🐇": @":rabbit2:",
                              @"🐉": @":dragon:",
                              @"🐐": @":goat:",
                              @"🐓": @":rooster:",
                              @"🐕": @":dog2:",
                              @"🐖": @":pig2:",
                              @"🐁": @":mouse2:",
                              @"🐂": @":ox:",
                              @"🐲": @":dragon_face:",
                              @"🐡": @":blowfish:",
                              @"🐊": @":crocodile:",
                              @"🐪": @":dromedary_camel:",
                              @"🐆": @":leopard:",
                              @"🐈": @":cat2:",
                              @"🐩": @":poodle:",
                              @"🐾": @":paw_prints:",
                              @"💐": @":bouquet:",
                              @"🌸": @":cherry_blossom:",
                              @"🌷": @":tulip:",
                              @"🍀": @":four_leaf_clover:",
                              @"🌹": @":rose:",
                              @"🌻": @":sunflower:",
                              @"🌺": @":hibiscus:",
                              @"🍁": @":maple_leaf:",
                              @"🍃": @":leaves:",
                              @"🍂": @":fallen_leaf:",
                              @"🌿": @":herb:",
                              @"🍄": @":mushroom:",
                              @"🌵": @":cactus:",
                              @"🌴": @":palm_tree:",
                              @"🌲": @":evergreen_tree:",
                              @"🌳": @":deciduous_tree:",
                              @"🌰": @":chestnut:",
                              @"🌱": @":seedling:",
                              @"🌼": @":blossum:",
                              @"🌾": @":ear_of_rice:",
                              @"🐚": @":shell:",
                              @"🌐": @":globe_with_meridians:",
                              @"🌞": @":sun_with_face:",
                              @"🌝": @":full_moon_with_face:",
                              @"🌚": @":new_moon_with_face:",
                              @"🌑": @":new_moon:",
                              @"🌒": @":waxing_crescent_moon:",
                              @"🌓": @":first_quarter_moon:",
                              @"🌔": @":waxing_gibbous_moon:",
                              @"🌕": @":full_moon:",
                              @"🌖": @":waning_gibbous_moon:",
                              @"🌗": @":last_quarter_moon:",
                              @"🌘": @":waning_crescent_moon:",
                              @"🌜": @":last_quarter_moon_with_face:",
                              @"🌛": @":first_quarter_moon_with_face:",
                              @"🌙": @":moon:",
                              @"🌍": @":earth_africa:",
                              @"🌎": @":earth_americas:",
                              @"🌏": @":earth_asia:",
                              @"🌋": @":volcano:",
                              @"🌌": @":milky_way:",
                              @"⛅": @":partly_sunny:",
                              @"🎍": @":bamboo:",
                              @"💝": @":gift_heart:",
                              @"🎎": @":dolls:",
                              @"🎒": @":school_satchel:",
                              @"🎓": @":mortar_board:",
                              @"🎏": @":flags:",
                              @"🎆": @":fireworks:",
                              @"🎇": @":sparkler:",
                              @"🎐": @":wind_chime:",
                              @"🎑": @":rice_scene:",
                              @"🎃": @":jack_o_lantern:",
                              @"👻": @":ghost:",
                              @"🎅": @":santa:",
                              @"🎱": @":8ball:",
                              @"⏰": @":alarm_clock:",
                              @"🍎": @":apple:",
                              @"🎨": @":art:",
                              @"🍼": @":baby_bottle:",
                              @"🎈": @":balloon:",
                              @"🍌": @":banana:",
                              @"📊": @":bar_chart:",
                              @"⚾": @":baseball:",
                              @"🏀": @":basketball:",
                              @"🛀": @":bath:",
                              @"🛁": @":bathtub:",
                              @"🔋": @":battery:",
                              @"🍺": @":beer:",
                              @"🍻": @":beers:",
                              @"🔔": @":bell:",
                              @"🍱": @":bento:",
                              @"🚴": @":bicyclist:",
                              @"👙": @":bikini:",
                              @"🎂": @":birthday:",
                              @"🃏": @":black_joker:",
                              @"✒": @":black_nib:",
                              @"📘": @":blue_book:",
                              @"💣": @":bomb:",
                              @"🔖": @":bookmark:",
                              @"📑": @":bookmark_tabs:",
                              @"📚": @":books:",
                              @"👢": @":boot:",
                              @"🎳": @":bowling:",
                              @"🍞": @":bread:",
                              @"💼": @":briefcase:",
                              @"💡": @":bulb:",
                              @"🍰": @":cake:",
                              @"📆": @":calendar:",
                              @"📲": @":calling:",
                              @"📷": @":camera:",
                              @"🍬": @":candy:",
                              @"📇": @":card_index:",
                              @"💿": @":cd:",
                              @"📉": @":chart_with_downwards_trend:",
                              @"📈": @":chart_with_upwards_trend:",
                              @"🍒": @":cherries:",
                              @"🍫": @":chocolate_bar:",
                              @"🎄": @":christmas_tree:",
                              @"🎬": @":clapper:",
                              @"📋": @":clipboard:",
                              @"📕": @":closed_book:",
                              @"🔐": @":closed_lock_with_key:",
                              @"🌂": @":closed_umbrella:",
                              @"♣": @":clubs:",
                              @"🍸": @":cocktail:",
                              @"☕": @":coffee:",
                              @"💻": @":computer:",
                              @"🎊": @":confetti_ball:",
                              @"🍪": @":cookie:",
                              @"🌽": @":corn:",
                              @"💳": @":credit_card:",
                              @"👑": @":crown:",
                              @"🔮": @":crystal_ball:",
                              @"🍛": @":curry:",
                              @"🍮": @":custard:",
                              @"🍡": @":dango:",
                              @"🎯": @":dart:",
                              @"📅": @":date:",
                              @"♦": @":diamonds:",
                              @"💵": @":dollar:",
                              @"🚪": @":door:",
                              @"🍩": @":doughnut:",
                              @"👗": @":dress:",
                              @"📀": @":dvd:",
                              @"📧": @":e-mail:",
                              @"🍳": @":egg:",
                              @"🍆": @":eggplant:",
                              @"🔌": @":electric_plug:",
                              @"✉": @":email:",
                              @"💶": @":euro:",
                              @"👓": @":eyeglasses:",
                              @"📠": @":fax:",
                              @"📁": @":file_folder:",
                              @"🍥": @":fish_cake:",
                              @"🎣": @":fishing_pole_and_fish:",
                              @"🔦": @":flashlight:",
                              @"💾": @":floppy_disk:",
                              @"🎴": @":flower_playing_cards:",
                              @"🏈": @":football:",
                              @"🍴": @":fork_and_knife:",
                              @"🍤": @":fried_shrimp:",
                              @"🍟": @":fries:",
                              @"🎲": @":game_die:",
                              @"💎": @":gem:",
                              @"🎁": @":gift:",
                              @"⛳": @":golf:",
                              @"🍇": @":grapes:",
                              @"🍏": @":green_apple:",
                              @"📗": @":green_book:",
                              @"🎸": @":guitar:",
                              @"🔫": @":gun:",
                              @"🍔": @":hamburger:",
                              @"🔨": @":hammer:",
                              @"👜": @":handbag:",
                              @"🎧": @":headphones:",
                              @"♥": @":hearts:",
                              @"🔆": @":high_brightness:",
                              @"👠": @":high_heel:",
                              @"🔪": @":hocho:",
                              @"🍯": @":honey_pot:",
                              @"🏇": @":horse_racing:",
                              @"⌛": @":hourglass:",
                              @"⏳": @":hourglass_flowing_sand:",
                              @"🍨": @":ice_cream:",
                              @"🍦": @":icecream:",
                              @"📥": @":inbox_tray:",
                              @"📨": @":incoming_envelope:",
                              @"📱": @":iphone:",
                              @"🏮": @":izakaya_lantern:",
                              @"👖": @":jeans:",
                              @"🔑": @":key:",
                              @"👘": @":kimono:",
                              @"📒": @":ledger:",
                              @"🍋": @":lemon:",
                              @"💄": @":lipstick:",
                              @"🔒": @":lock:",
                              @"🔏": @":lock_with_ink_pen:",
                              @"🍭": @":lollipop:",
                              @"➿": @":loop:",
                              @"📢": @":loudspeaker:",
                              @"🔅": @":low_brightness:",
                              @"🔍": @":mag:",
                              @"🔎": @":mag_right:",
                              @"🀄": @":mahjong:",
                              @"📫": @":mailbox:",
                              @"📪": @":mailbox_closed:",
                              @"📬": @":mailbox_with_mail:",
                              @"📭": @":mailbox_with_no_mail:",
                              @"👞": @":mans_shoe:",
                              @"🍖": @":meat_on_bone:",
                              @"📣": @":mega:",
                              @"🍈": @":melon:",
                              @"📝": @":memo:",
                              @"🎤": @":microphone:",
                              @"🔬": @":microscope:",
                              @"💽": @":minidisc:",
                              @"💸": @":money_with_wings:",
                              @"💰": @":moneybag:",
                              @"🚵": @":mountain_bicyclist:",
                              @"🎥": @":movie_camera:",
                              @"🎹": @":musical_keyboard:",
                              @"🎼": @":musical_score:",
                              @"🔇": @":mute:",
                              @"📛": @":name_badge:",
                              @"👔": @":necktie:",
                              @"📰": @":newspaper:",
                              @"🔕": @":no_bell:",
                              @"📓": @":notebook:",
                              @"📔": @":notebook_with_decorative_cover:",
                              @"🔩": @":nut_and_bolt:",
                              @"🍢": @":oden:",
                              @"📂": @":open_file_folder:",
                              @"📙": @":orange_book:",
                              @"📤": @":outbox_tray:",
                              @"📄": @":page_facing_up:",
                              @"📃": @":page_with_curl:",
                              @"📟": @":pager:",
                              @"📎": @":paperclip:",
                              @"🍑": @":peach:",
                              @"🍐": @":pear:",
                              @"✏": @":pencil2:",
                              @"☎": @":phone:",
                              @"💊": @":pill:",
                              @"🍍": @":pineapple:",
                              @"🍕": @":pizza:",
                              @"📯": @":postal_horn:",
                              @"📮": @":postbox:",
                              @"👝": @":pouch:",
                              @"🍗": @":poultry_leg:",
                              @"💷": @":pound:",
                              @"👛": @":purse:",
                              @"📌": @":pushpin:",
                              @"📻": @":radio:",
                              @"🍜": @":ramen:",
                              @"🎀": @":ribbon:",
                              @"🍚": @":rice:",
                              @"🍙": @":rice_ball:",
                              @"🍘": @":rice_cracker:",
                              @"💍": @":ring:",
                              @"🏉": @":rugby_football:",
                              @"🎽": @":running_shirt_with_sash:",
                              @"🍶": @":sake:",
                              @"👡": @":sandal:",
                              @"📡": @":satellite:",
                              @"🎷": @":saxophone:",
                              @"✂": @":scissors:",
                              @"📜": @":scroll:",
                              @"💺": @":seat:",
                              @"🍧": @":shaved_ice:",
                              @"👕": @":shirt:",
                              @"🚿": @":shower:",
                              @"🎿": @":ski:",
                              @"🚬": @":smoking:",
                              @"🏂": @":snowboarder:",
                              @"⚽": @":soccer:",
                              @"🔉": @":sound:",
                              @"👾": @":space_invader:",
                              @"♠": @":spades:",
                              @"🍝": @":spaghetti:",
                              @"🔊": @":speaker:",
                              @"🍲": @":stew:",
                              @"📏": @":straight_ruler:",
                              @"🍓": @":strawberry:",
                              @"🏄": @":surfer:",
                              @"🍣": @":sushi:",
                              @"🍠": @":sweet_potato:",
                              @"🏊": @":swimmer:",
                              @"💉": @":syringe:",
                              @"🎉": @":tada:",
                              @"🎋": @":tanabata_tree:",
                              @"🍊": @":tangerine:",
                              @"🍵": @":tea:",
                              @"📞": @":telephone_receiver:",
                              @"🔭": @":telescope:",
                              @"🎾": @":tennis:",
                              @"🚽": @":toilet:",
                              @"🍅": @":tomato:",
                              @"🎩": @":tophat:",
                              @"📐": @":triangular_ruler:",
                              @"🏆": @":trophy:",
                              @"🍹": @":tropical_drink:",
                              @"🎺": @":trumpet:",
                              @"📺": @":tv:",
                              @"🔓": @":unlock:",
                              @"📼": @":vhs:",
                              @"📹": @":video_camera:",
                              @"🎮": @":video_game:",
                              @"🎻": @":violin:",
                              @"⌚": @":watch:",
                              @"🍉": @":watermelon:",
                              @"🍷": @":wine_glass:",
                              @"👚": @":womans_clothes:",
                              @"👒": @":womans_hat:",
                              @"🔧": @":wrench:",
                              @"💴": @":yen:",
                              @"🚡": @":aerial_tramway:",
                              @"✈": @":airplane:",
                              @"🚑": @":ambulance:",
                              @"⚓": @":anchor:",
                              @"🚛": @":articulated_lorry:",
                              @"🏧": @":atm:",
                              @"🏦": @":bank:",
                              @"💈": @":barber:",
                              @"🔰": @":beginner:",
                              @"🚲": @":bike:",
                              @"🚙": @":blue_car:",
                              @"⛵": @":boat:",
                              @"🌉": @":bridge_at_night:",
                              @"🚅": @":bullettrain_front:",
                              @"🚄": @":bullettrain_side:",
                              @"🚌": @":bus:",
                              @"🚏": @":busstop:",
                              @"🚗": @":car:",
                              @"🎠": @":carousel_horse:",
                              @"🏁": @":checkered_flag:",
                              @"⛪": @":church:",
                              @"🎪": @":circus_tent:",
                              @"🌇": @":city_sunrise:",
                              @"🌆": @":city_sunset:",
                              @"🚧": @":construction:",
                              @"🏪": @":convenience_store:",
                              @"🎌": @":crossed_flags:",
                              @"🏬": @":department_store:",
                              @"🏰": @":european_castle:",
                              @"🏤": @":european_post_office:",
                              @"🏭": @":factory:",
                              @"🎡": @":ferris_wheel:",
                              @"🚒": @":fire_engine:",
                              @"⛲": @":fountain:",
                              @"⛽": @":fuelpump:",
                              @"🚁": @":helicopter:",
                              @"🏥": @":hospital:",
                              @"🏨": @":hotel:",
                              @"♨": @":hotsprings:",
                              @"🏠": @":house:",
                              @"🏡": @":house_with_garden:",
                              @"🗾": @":japan:",
                              @"🏯": @":japanese_castle:",
                              @"🚈": @":light_rail:",
                              @"🏩": @":love_hotel:",
                              @"🚐": @":minibus:",
                              @"🚝": @":monorail:",
                              @"🗻": @":mount_fuji:",
                              @"🚠": @":mountain_cableway:",
                              @"🚞": @":mountain_railway:",
                              @"🗿": @":moyai:",
                              @"🏢": @":office:",
                              @"🚘": @":oncoming_automobile:",
                              @"🚍": @":oncoming_bus:",
                              @"🚔": @":oncoming_police_car:",
                              @"🚖": @":oncoming_taxi:",
                              @"🎭": @":performing_arts:",
                              @"🚓": @":police_car:",
                              @"🏣": @":post_office:",
                              @"🚃": @":railway_car:",
                              @"🌈": @":rainbow:",
                              @"🚀": @":rocket:",
                              @"🎢": @":roller_coaster:",
                              @"🚨": @":rotating_light:",
                              @"📍": @":round_pushpin:",
                              @"🚣": @":rowboat:",
                              @"🏫": @":school:",
                              @"🚢": @":ship:",
                              @"🎰": @":slot_machine:",
                              @"🚤": @":speedboat:",
                              @"🌠": @":stars:",
                              @"🌃": @":city-night:",
                              @"🚉": @":station:",
                              @"🗽": @":statue_of_liberty:",
                              @"🚂": @":steam_locomotive:",
                              @"🌅": @":sunrise:",
                              @"🌄": @":sunrise_over_mountains:",
                              @"🚟": @":suspension_railway:",
                              @"🚕": @":taxi:",
                              @"⛺": @":tent:",
                              @"🎫": @":ticket:",
                              @"🗼": @":tokyo_tower:",
                              @"🚜": @":tractor:",
                              @"🚥": @":traffic_light:",
                              @"🚆": @":train2:",
                              @"🚊": @":tram:",
                              @"🚩": @":triangular_flag_on_post:",
                              @"🚎": @":trolleybus:",
                              @"🚚": @":truck:",
                              @"🚦": @":vertical_traffic_light:",
                              @"⚠": @":warning:",
                              @"💒": @":wedding:",
                              @"🇯🇵": @":jp:",
                              @"🇰🇷": @":kr:",
                              @"🇨🇳": @":cn:",
                              @"🇺🇸": @":us:",
                              @"🇫🇷": @":fr:",
                              @"🇪🇸": @":es:",
                              @"🇮🇹": @":it:",
                              @"🇷🇺": @":ru:",
                              @"🇬🇧": @":gb:",
                              @"🇩🇪": @":de:",
                              @"💯": @":100:",
                              @"🔢": @":1234:",
                              @"🅰": @":a:",
                              @"🆎": @":ab:",
                              @"🔤": @":abc:",
                              @"🔡": @":abcd:",
                              @"🉑": @":accept:",
                              @"♒": @":aquarius:",
                              @"♈": @":aries:",
                              @"◀": @":arrow_backward:",
                              @"⏬": @":arrow_double_down:",
                              @"⏫": @":arrow_double_up:",
                              @"⬇": @":arrow_down:",
                              @"🔽": @":arrow_down_small:",
                              @"▶": @":arrow_forward:",
                              @"⤵": @":arrow_heading_down:",
                              @"⤴": @":arrow_heading_up:",
                              @"⬅": @":arrow_left:",
                              @"↙": @":arrow_lower_left:",
                              @"↘": @":arrow_lower_right:",
                              @"➡": @":arrow_right:",
                              @"↪": @":arrow_right_hook:",
                              @"⬆": @":arrow_up:",
                              @"↕": @":arrow_up_down:",
                              @"🔼": @":arrow_up_small:",
                              @"↖": @":arrow_upper_left:",
                              @"↗": @":arrow_upper_right:",
                              @"🔃": @":arrows_clockwise:",
                              @"🔄": @":arrows_counterclockwise:",
                              @"🅱": @":b:",
                              @"🚼": @":baby_symbol:",
                              @"🛄": @":baggage_claim:",
                              @"☑": @":ballot_box_with_check:",
                              @"‼": @":bangbang:",
                              @"⚫": @":black_circle:",
                              @"🔲": @":black_square_button:",
                              @"♋": @":cancer:",
                              @"🔠": @":capital_abcd:",
                              @"♑": @":capricorn:",
                              @"💹": @":chart:",
                              @"🚸": @":children_crossing:",
                              @"🎦": @":cinema:",
                              @"🆑": @":cl:",
                              @"🕐": @":clock1:",
                              @"🕙": @":clock10:",
                              @"🕥": @":clock1030:",
                              @"🕚": @":clock11:",
                              @"🕦": @":clock1130:",
                              @"🕛": @":clock12:",
                              @"🕧": @":clock1230:",
                              @"🕜": @":clock130:",
                              @"🕑": @":clock2:",
                              @"🕝": @":clock230:",
                              @"🕒": @":clock3:",
                              @"🕞": @":clock330:",
                              @"🕓": @":clock4:",
                              @"🕟": @":clock430:",
                              @"🕔": @":clock5:",
                              @"🕠": @":clock530:",
                              @"🕕": @":clock6:",
                              @"🕡": @":clock630:",
                              @"🕖": @":clock7:",
                              @"🕢": @":clock730:",
                              @"🕗": @":clock8:",
                              @"🕣": @":clock830:",
                              @"🕘": @":clock9:",
                              @"🕤": @":clock930:",
                              @"㊗": @":congratulations:",
                              @"🆒": @":cool:",
                              @"©": @":copyright:",
                              @"➰": @":curly_loop:",
                              @"💱": @":currency_exchange:",
                              @"🛃": @":customs:",
                              @"💠": @":diamond_shape_with_a_dot_inside:",
                              @"🚯": @":do_not_litter:",
                              @"8⃣": @":eight:",
                              @"✴": @":eight_pointed_black_star:",
                              @"✳": @":eight_spoked_asterisk:",
                              @"🔚": @":end:",
                              @"⏩": @":fast_forward:",
                              @"5⃣": @":five:",
                              @"4⃣": @":four:",
                              @"🆓": @":free:",
                              @"♊": @":gemini:",
                              @"#⃣": @":hash:",
                              @"💟": @":heart_decoration:",
                              @"✔": @":heavy_check_mark:",
                              @"➗": @":heavy_division_sign:",
                              @"💲": @":heavy_dollar_sign:",
                              @"➖": @":heavy_minus_sign:",
                              @"✖": @":heavy_multiplication_x:",
                              @"➕": @":heavy_plus_sign:",
                              @"🆔": @":id:",
                              @"🉐": @":ideograph_advantage:",
                              @"ℹ": @":information_source:",
                              @"⁉": @":interrobang:",
                              @"🔟": @":keycap_ten:",
                              @"🈁": @":koko:",
                              @"🔵": @":large_blue_circle:",
                              @"🔷": @":large_blue_diamond:",
                              @"🔶": @":large_orange_diamond:",
                              @"🛅": @":left_luggage:",
                              @"↔": @":left_right_arrow:",
                              @"↩": @":leftwards_arrow_with_hook:",
                              @"♌": @":leo:",
                              @"♎": @":libra:",
                              @"🔗": @":link:",
                              @"Ⓜ": @":m:",
                              @"🚹": @":mens:",
                              @"🚇": @":metro:",
                              @"📴": @":mobile_phone_off:",
                              @"❎": @":negative_squared_cross_mark:",
                              @"🆕": @":new:",
                              @"🆖": @":ng:",
                              @"9⃣": @":nine:",
                              @"🚳": @":no_bicycles:",
                              @"⛔": @":no_entry:",
                              @"🚫": @":no_entry_sign:",
                              @"📵": @":no_mobile_phones:",
                              @"🚷": @":no_pedestrians:",
                              @"🚭": @":no_smoking:",
                              @"🚱": @":non-potable_water:",
                              @"⭕": @":o:",
                              @"🅾": @":o2:",
                              @"🆗": @":ok:",
                              @"🔛": @":on:",
                              @"1⃣": @":one:",
                              @"⛎": @":ophiuchus:",
                              @"🅿": @":parking:",
                              @"〽": @":part_alternation_mark:",
                              @"🛂": @":passport_control:",
                              @"♓": @":pisces:",
                              @"🚰": @":potable_water:",
                              @"🚮": @":put_litter_in_its_place:",
                              @"🔘": @":radio_button:",
                              @"♻": @":recycle:",
                              @"🔴": @":red_circle:",
                              @"®": @":registered:",
                              @"🔁": @":repeat:",
                              @"🔂": @":repeat_one:",
                              @"🚻": @":restroom:",
                              @"⏪": @":rewind:",
                              @"🈂": @":sa:",
                              @"♐": @":sagittarius:",
                              @"♏": @":scorpius:",
                              @"㊙": @":secret:",
                              @"7⃣": @":seven:",
                              @"📶": @":signal_strength:",
                              @"6⃣": @":six:",
                              @"🔯": @":six_pointed_star:",
                              @"🔹": @":small_blue_diamond:",
                              @"🔸": @":small_orange_diamond:",
                              @"🔺": @":small_red_triangle:",
                              @"🔻": @":small_red_triangle_down:",
                              @"🔜": @":soon:",
                              @"🆘": @":sos:",
                              @"🔣": @":symbols:",
                              @"♉": @":taurus:",
                              @"3⃣": @":three:",
                              @"™": @":tm:",
                              @"🔝": @":top:",
                              @"🔱": @":trident:",
                              @"🔀": @":twisted_rightwards_arrows:",
                              @"2⃣": @":two:",
                              @"🈹": @":u5272:",
                              @"🈴": @":u5408:",
                              @"🈺": @":u55b6:",
                              @"🈯": @":u6307:",
                              @"🈷": @":u6708:",
                              @"🈶": @":u6709:",
                              @"🈵": @":u6e80:",
                              @"🈚": @":u7121:",
                              @"🈸": @":u7533:",
                              @"🈲": @":u7981:",
                              @"🈳": @":u7a7a:",
                              @"🔞": @":underage:",
                              @"🆙": @":up:",
                              @"📳": @":vibration_mode:",
                              @"♍": @":virgo:",
                              @"🆚": @":vs:",
                              @"〰": @":wavy_dash:",
                              @"🚾": @":wc:",
                              @"♿": @":wheelchair:",
                              @"✅": @":white_check_mark:",
                              @"⚪": @":white_circle:",
                              @"💮": @":white_flower:",
                              @"🔳": @":white_square_button:",
                              @"🚺": @":womens:",
                              @"❌": @":x:",
                              @"0⃣": @":zero:"
                              };
        
        unicodeAndEmojiDic = @{
                              @":1234:" : @"🔢",
                              @":incoming_envelope:" : @"📨",
                              @":snowman:" : @"⛄",
                              @":droplet:" : @"💧",
                              @":fire_engine:" : @"🚒",
                              @":cow:" : @"🐮",
                              @":scissors:" : @"✂",
                              @":cactus:" : @"🌵",
                              @":evergreen_tree:" : @"🌲",
                              @":ok_hand:" : @"👌",
                              @":alarm_clock:" : @"⏰",
                              @":8ball:" : @"🎱",
                              @":outbox_tray:" : @"📤",
                              @":cherries:" : @"🍒",
                              @":customs:" : @"🛃",
                              @":astonished:" : @"😲",
                              @":broken_heart:" : @"💔",
                              @":newspaper:" : @"📰",
                              @":date:" : @"📅",
                              @":tv:" : @"📺",
                              @":dancers:" : @"👯",
                              @":relaxed:" : @"☺",
                              @":mailbox_with_no_mail:" : @"📭",
                              @":arrow_lower_left:" : @"↙",
                              @":wheelchair:" : @"♿",
                              @":oden:" : @"🍢",
                              @":no_mobile_phones:" : @"📵",
                              @":cookie:" : @"🍪",
                              @":santa:" : @"🎅",
                              @":end:" : @"🔚",
                              @":leo:" : @"♌",
                              @":poodle:" : @"🐩",
                              @":spades:" : @"♠",
                              @":school_satchel:" : @"🎒",
                              @":lipstick:" : @"💄",
                              @":u7121:" : @"🈚",
                              @":balloon:" : @"🎈",
                              @":warning:" : @"⚠",
                              @":sagittarius:" : @"♐",
                              @":fork_and_knife:" : @"🍴",
                              @":bug:" : @"🐛",
                              @":trolleybus:" : @"🚎",
                              @":mans_shoe:" : @"👞",
                              @":full_moon:" : @"🌕",
                              @":persevere:" : @"😣",
                              @":honey_pot:" : @"🍯",
                              @":sound:" : @"🔉",
                              @":yum:" : @"😋",
                              @":alien:" : @"👽",
                              @":mahjong:" : @"🀄",
                              @":red_circle:" : @"🔴",
                              @":partly_sunny:" : @"⛅",
                              @":lock_with_ink_pen:" : @"🔏",
                              @":bar_chart:" : @"📊",
                              @":guitar:" : @"🎸",
                              @":movie_camera:" : @"🎥",
                              @":sweet_potato:" : @"🍠",
                              @":custard:" : @"🍮",
                              @":dart:" : @"🎯",
                              @":cat:" : @"🐱",
                              @":chicken:" : @"🐔",
                              @":earth_africa:" : @"🌍",
                              @":muscle:" : @"💪",
                              @":jp:" : @"🇯🇵",
                              @":gift_heart:" : @"💝",
                              @":arrow_down_small:" : @"🔽",
                              @":person_frowning:" : @"🙍",
                              @":moneybag:" : @"💰",
                              @":card_index:" : @"📇",
                              @":fast_forward:" : @"⏩",
                              @":tiger:" : @"🐯",
                              @":love_letter:" : @"💌",
                              @":frog:" : @"🐸",
                              @":us:" : @"🇺🇸",
                              @":family:" : @"👪",
                              @":skull:" : @"💀",
                              @":keycap_ten:" : @"🔟",
                              @":blue_car:" : @"🚙",
                              @":arrow_double_up:" : @"⏫",
                              @":tanabata_tree:" : @"🎋",
                              @":sunrise:" : @"🌅",
                              @":flower_playing_cards:" : @"🎴",
                              @":hourglass:" : @"⌛",
                              @":factory:" : @"🏭",
                              @":left_right_arrow:" : @"↔",
                              @":sa:" : @"🈂",
                              @":honeybee:" : @"🐝",
                              @":wind_chime:" : @"🎐",
                              @":musical_score:" : @"🎼",
                              @":angry:" : @"😠",
                              @":mute:" : @"🔇",
                              @":post_office:" : @"🏣",
                              @":couplekiss:" : @"💏",
                              @":bus:" : @"🚌",
                              @":registered:" : @"®",
                              @":clock2:" : @"🕑",
                              @":clock5:" : @"🕔",
                              @":dragon:" : @"🐉",
                              @":clock8:" : @"🕗",
                              @":fallen_leaf:" : @"🍂",
                              @":kissing_smiling_eyes:" : @"😙",
                              @":blush:" : @"😊",
                              @":raised_hands:" : @"🙌",
                              @":moon:" : @"🌙",
                              @":no_pedestrians:" : @"🚷",
                              @":shower:" : @"🚿",
                              @":star2:" : @"🌟",
                              @":fountain:" : @"⛲",
                              @":paperclip:" : @"📎",
                              @":repeat_one:" : @"🔂",
                              @":battery:" : @"🔋",
                              @":helicopter:" : @"🚁",
                              @":game_die:" : @"🎲",
                              @":monkey:" : @"🐒",
                              @":fireworks:" : @"🎆",
                              @":u6709:" : @"🈶",
                              @":ru:" : @"🇷🇺",
                              @":wavy_dash:" : @"〰",
                              @":nail_care:" : @"💅",
                              @":clock330:" : @"🕞",
                              @":de:" : @"🇩🇪",
                              @":convenience_store:" : @"🏪",
                              @":inbox_tray:" : @"📥",
                              @":city_sunrise:" : @"🌇",
                              @":sob:" : @"😭",
                              @":computer:" : @"💻",
                              @":confused:" : @"😕",
                              @":small_orange_diamond:" : @"🔸",
                              @":rage:" : @"😡",
                              @":no_mouth:" : @"😶",
                              @":closed_umbrella:" : @"🌂",
                              @":surfer:" : @"🏄",
                              @":arrow_double_down:" : @"⏬",
                              @":house_with_garden:" : @"🏡",
                              @":jeans:" : @"👖",
                              @":sparkling_heart:" : @"💖",
                              @":closed_book:" : @"📕",
                              @":performing_arts:" : @"🎭",
                              @":flags:" : @"🎏",
                              @":bento:" : @"🍱",
                              @":black_square_button:" : @"🔲",
                              @":bride_with_veil:" : @"👰",
                              @":clock730:" : @"🕢",
                              @":hankey:" : @"💩",
                              @":negative_squared_cross_mark:" : @"❎",
                              @":cloud:" : @"☁",
                              @":paw_prints:" : @"🐾",
                              @":postal_horn:" : @"📯",
                              @":bicyclist:" : @"🚴",
                              @":truck:" : @"🚚",
                              @":person_with_blond_hair:" : @"👱",
                              @":dolphin:" : @"🐬",
                              @":arrow_heading_down:" : @"⤵",
                              @":tropical_fish:" : @"🐠",
                              @":sunrise_over_mountains:" : @"🌄",
                              @":sleepy:" : @"😪",
                              @":ice_cream:" : @"🍨",
                              @":waxing_gibbous_moon:" : @"🌔",
                              @":womens:" : @"🚺",
                              @":video_game:" : @"🎮",
                              @":nine:" : @"9⃣",
                              @":european_castle:" : @"🏰",
                              @":white_flower:" : @"💮",
                              @":trumpet:" : @"🎺",
                              @":monorail:" : @"🚝",
                              @":open_file_folder:" : @"📂",
                              @":older_woman:" : @"👵",
                              @":heavy_minus_sign:" : @"➖",
                              @":tent:" : @"⛺",
                              @":blowfish:" : @"🐡",
                              @":yellow_heart:" : @"💛",
                              @":tm:" : @"™",
                              @":point_up:" : @"☝",
                              @":green_heart:" : @"💚",
                              @":panda_face:" : @"🐼",
                              @":o:" : @"⭕",
                              @":kissing_cat:" : @"😽",
                              @":city_sunset:" : @"🌆",
                              @":small_red_triangle_down:" : @"🔻",
                              @":horse_racing:" : @"🏇",
                              @":heavy_plus_sign:" : @"➕",
                              @":pizza:" : @"🍕",
                              @":speak_no_evil:" : @"🙊",
                              @":coffee:" : @"☕",
                              @":seedling:" : @"🌱",
                              @":stew:" : @"🍲",
                              @":large_blue_circle:" : @"🔵",
                              @":bread:" : @"🍞",
                              @":imp:" : @"👿",
                              @":cl:" : @"🆑",
                              @":car:" :@"🚗",
                              @":monkey_face:" : @"🐵",
                              @":bullettrain_front:" : @"🚅",
                              @":punch:" : @"👊",
                              @":eyeglasses:" : @"👓",
                              @":o2:" : @"🅾",
                              @":notebook_with_decorative_cover:" : @"📔",
                              @":tractor:" : @"🚜",
                              @":blue_book:" : @"📘",
                              @":smoking:" : @"🚬",
                              @":watermelon:" : @"🍉",
                              @":mouse:" : @"🐭",
                              @":oncoming_automobile:" : @"🚘",
                              @":raised_hand:" : @"🙋",
                              @":arrow_backward:" : @"◀",
                              @":arrow_down:" : @"⬇",
                              @":file_folder:" : @"📁",
                              @":wrench:" : @"🔧",
                              @":capricorn:" : @"♑",
                              @":unamused:" : @"😒",
                              @":pineapple:" : @"🍍",
                              @":microscope:" : @"🔬",
                              @":corn:" : @"🌽",
                              @":smirk_cat:" : @"😼",
                              @":zero:" : @"0⃣",
                              @":hourglass_flowing_sand:" : @"⏳",
                              @":walking:" : @"🚶",
                              @":-1:" : @"👎",
                              @":girl:" : @"👧",
                              @":pill:" : @"💊",
                              @":peach:" : @"🍑",
                              @":light_rail:" : @"🚈",
                              @":recycle:" : @"♻",
                              @":name_badge:" : @"📛",
                              @":hotsprings:" : @"♨",
                              @":running_shirt_with_sash:" : @"🎽",
                              @":point_up_2:" : @"👆",
                              @":beginner:" : @"🔰",
                              @":laughing:" : @"😆",
                              @":beer:" : @"🍺",
                              @":taxi:" : @"🚕",
                              @":speedboat:" : @"🚤",
                              @":love_hotel:" : @"🏩",
                              @":whale:" : @"🐳",
                              @":secret:" : @"㊙",
                              @":shirt:" : @"👕",
                              @":rat:" : @"🐀",
                              @":x:" : @"❌",
                              @":atm:" : @"🏧",
                              @":cn:" : @"🇨🇳",
                              @":kissing:" : @"😗",
                              @":eyes:" : @"👀",
                              @":arrow_upper_right:" : @"↗",
                              @":black_nib:" : @"✒",
                              @":confetti_ball:" : @"🎊",
                              @":chocolate_bar:" : @"🍫",
                              @":bookmark_tabs:" : @"📑",
                              @":pouting_cat:" : @"😾",
                              @":steam_locomotive:" : @"🚂",
                              @":chart_with_downwards_trend:" : @"📉",
                              @":low_brightness:" : @"🔅",
                              @":construction:" : @"🚧",
                              @":blue_heart:" : @"💙",
                              @":earth_americas:" : @"🌎",
                              @":clock1230:" : @"🕧",
                              @":weary:" : @"😩",
                              @":es:" : @"🇪🇸",
                              @":angel:" : @"👼",
                              @":euro:" : @"💶",
                              @":arrow_heading_up:" : @"⤴",
                              @":guardsman:" : @"💂",
                              @":fuelpump:" : @"⛽",
                              @":horse:" : @"🐴",
                              @":train2:" : @"🚆",
                              @":crying_cat_face:" : @"😿",
                              @":virgo:" : @"♍",
                              @":electric_plug:" : @"🔌",
                              @":earth_asia:" : @"🌏",
                              @":shit:" : @"💩",
                              @":triangular_ruler:" : @"📐",
                              @":tulip:" : @"🌷",
                              @":passport_control:" : @"🛂",
                              @":top:" : @"🔝",
                              @":snowflake:" : @"❄",
                              @":minidisc:" : @"💽",
                              @":thumbsup:" : @"👍",
                              @":u6307:" : @"🈯",
                              @":man:" : @"👨",
                              @":large_orange_diamond:" : @"🔶",
                              @":arrows_counterclockwise:" : @"🔄",
                              @":dragon_face:" : @"🐲",
                              @":palm_tree:" : @"🌴",
                              @":briefcase:" : @"💼",
                              @":three:" : @"3⃣",
                              @":hand:" : @"✋",
                              @":rice_scene:" : @"🎑",
                              @":floppy_disk:" : @"💾",
                              @":clock10:" : @"🕙",
                              @":fried_shrimp:" : @"🍤",
                              @":six:" : @"6⃣",
                              @":sheep:" : @"🐑",
                              @":rabbit2:" : @"🐇",
                              @":small_blue_diamond:" : @"🔹",
                              @":two_men_holding_hands:" : @"👬",
                              @":five:" : @"5⃣",
                              @":on:" : @"🔛",
                              @":heavy_division_sign:" : @"➗",
                              @":sleeping:" : @"😴",
                              @":tophat:" : @"🎩",
                              @":fish:" : @"🐟",
                              @":white_check_mark:" : @"✅",
                              @":tea:" : @"🍵",
                              @":diamonds:" : @"♦",
                              @":wink2:" : @"😜",
                              @":watch:" : @"⌚",
                              @":football:" : @"🏈",
                              @":dizzy:" : @"💫",
                              @":mortar_board:" : @"🎓",
                              @":baby_chick:" : @"🐤",
                              @":scream_cat:" : @"🙀",
                              @":turtle:" : @"🐢",
                              @":zzz:" : @"💤",
                              @":email:" : @"✉",
                              @":clock12:" : @"🕛",
                              @":triumph:" : @"😤",
                              @":kissing_heart:" : @"😘",
                              @":older_man:" : @"👴",
                              @":pound:" : @"💷",
                              @":clock430:" : @"🕟",
                              @":bathtub:" : @"🛁",
                              @":white_square_button:" : @"🔳",
                              @":japanese_goblin:" : @"👺",
                              @":pencil2:" : @"✏",
                              @":question:" : @"❓",
                              @":first_quarter_moon_with_face:" : @"🌛",
                              @":libra:" : @"♎",
                              @":seat:" : @"💺",
                              @":roller_coaster:" : @"🎢",
                              @":pisces:" : @"♓",
                              @":a:" : @"🅰",
                              @":construction_worker:" : @"👷",
                              @":dash:" : @"💨",
                              @":clapper:" : @"🎬",
                              @":grapes:" : @"🍇",
                              @":high_heel:" : @"👠",
                              @":heartbeat:" : @"💓",
                              @":iphone:" : @"📱",
                              @":hibiscus:" : @"🌺",
                              @":nose:" : @"👃",
                              @":sweat_drops:" : @"💦",
                              @":aquarius:" : @"♒",
                              @":heart_eyes:" : @"😍",
                              @":clock830:" : @"🕣",
                              @":no_entry:" : @"⛔",
                              @":wolf:" : @"🐺",
                              @":statue_of_liberty:" : @"🗽",
                              @":u6e80:" : @"🈵",
                              @":bowling:" : @"🎳",
                              @":eight:" : @"8⃣",
                              @":no_smoking:" : @"🚭",
                              @":bikini:" : @"👙",
                              @":bank:" : @"🏦",
                              @":scorpius:" : @"♏",
                              @":sunflower:" : @"🌻",
                              @":clock3:" : @"🕒",
                              @":clock6:" : @"🕕",
                              @":fr:" : @"🇫🇷",
                              @":clock9:" : @"🕘",
                              @":rabbit:" : @"🐰",
                              @":school:" : @"🏫",
                              @":dollar:" : @"💵",
                              @":chestnut:" : @"🌰",
                              @":koko:" : @"🈁",
                              @";)" : @"😉",
                              @":aries:" : @"♈",
                              @":church:" : @"⛪",
                              @":currency_exchange:" : @"💱",
                              @":memo:" : @"📝",
                              @":point_right:" : @"👉",
                              @":arrow_forward:" : @"▶",
                              @":fearful:" : @"😨",
                              @":hammer:" : @"🔨",
                              @":hatching_chick:" : @"🐣",
                              @":european_post_office:" : @"🏤",
                              @":interrobang:" : @"⁉",
                              @":pig2:" : @"🐖",
                              @":articulated_lorry:" : @"🚛",
                              @":womans_clothes:" : @"👚",
                              @":tropical_drink:" : @"🍹",
                              @":worried:" : @"😟",
                              @":minibus:" : @"🚐",
                              @":up:" : @"🆙",
                              @":boar:" : @"🐗",
                              @":relieved:" : @"😥",
                              @":izakaya_lantern:" : @"🏮",
                              @":sparkles:" : @"✨",
                              @":snail:" : @"🐌",
                              @":rowboat:" : @"🚣",
                              @":dango:" : @"🍡",
                              @":clap:" : @"👏",
                              @":two_women_holding_hands:" : @"👭",
                              @":four:" : @"4⃣",
                              @":children_crossing:" : @"🚸",
                              @":wave:" : @"👋",
                              @":sunglasses:" : @"😎",
                              @":chart:" : @"💹",
                              @":mushroom:" : @"🍄",
                              @":clipboard:" : @"📋",
                              @":couple_with_heart:" : @"💑",
                              @":do_not_litter:" : @"🚯",
                              @":headphones:" : @"🎧",
                              @":sushi:" : @"🍣",
                              @":dress:" : @"👗",
                              @":mag_right:" : @"🔎",
                              @":heartpulse:" : @"💗",
                              @":wink:" : @"😉",
                              @":smiley_cat:" : @"😺",
                              @":cherry_blossom:" : @"🌸",
                              @":bear:" : @"🐻",
                              @":tongue:" : @"👅",
                              @":books:" : @"📚",
                              @":arrows_clockwise:" : @"🔃",
                              @":ab:" : @"🆎",
                              @":-)" : @"😃",
                              @":bath:" : @"🛀",
                              @":kissing_closed_eyes:" : @"😚",
                              @":oncoming_police_car:" : @"🚔",
                              @":airplane:" : @"✈",
                              @":twisted_rightwards_arrows:" : @"🔀",
                              @";-)" : @"😉",
                              @":two:" : @"2⃣",
                              @":m:" : @"Ⓜ",
                              @":man_with_gua_pi_mao:" : @"👲",
                              @":gift:" : @"🎁",
                              @":traffic_light:" : @"🚥",
                              @":racehorse:" : @"🐎",
                              @":accept:" : @"🉑",
                              @":checkered_flag:" : @"🏁",
                              @":sunny:" : @"☀",
                              @":calendar:" : @"📆",
                              @":microphone:" : @"🎤",
                              @":aerial_tramway:" : @"🚡",
                              @":dog:" : @"🐶",
                              @":notebook:" : @"📓",
                              @":eggplant:" : @"🍆",
                              @":princess:" : @"👸",
                              @":symbols:" : @"🔣",
                              @":bullettrain_side:" : @"🚄",
                              @":carousel_horse:" : @"🎠",
                              @":city-night:" : @"🌃",
                              @":information_desk_person:" : @"💁",
                              @":it:" : @"🇮🇹",
                              @":cyclone:" : @"🌀",
                              @":bridge_at_night:" : @"🌉",
                              @":video_camera:" : @"📹",
                              @":no_bell:" : @"🔕",
                              @":tokyo_tower:" : @"🗼",
                              @":oncoming_bus:" : @"🚍",
                              @":ski:" : @"🎿",
                              @":open_mouth:" : @"😮",
                              @":mobile_phone_off:" : @"📴",
                              @":ship:" : @"🚢",
                              @":cop:" : @"👮",
                              @":u55b6:" : @"🈺",
                              @":gb:" : @"🇬🇧",
                              @":boot:" : @"👢",
                              @":clock1130:" : @"🕦",
                              @":copyright:" : @"©",
                              @":ribbon:" : @"🎀",
                              @":mount_fuji:" : @"🗻",
                              @":flushed:" : @"😳",
                              @":wine_glass:" : @"🍷",
                              @":office:" : @"🏢",
                              @":telescope:" : @"🔭",
                              @":small_red_triangle:" : @"🔺",
                              @":point_left:" : @"👈",
                              @":boy:" : @"👦",
                              @":new_moon_with_face:" : @"🌚",
                              @":mouse2:" : @"🐁",
                              @":leopard:" : @"🐆",
                              @":bike:" : @"🚲",
                              @":vhs:" : @"📼",
                              @":penguin:" : @"🐧",
                              @":ticket:" : @"🎫",
                              @":mega:" : @"📣",
                              @":banana:" : @"🍌",
                              @":beers:" : @"🍻",
                              @":anchor:" : @"⚓",
                              @":hash:" : @"#⃣",
                              @":sparkler:" : @"🎇",
                              @":grin:" : @"😁",
                              @":fax:" : @"📠",
                              @":umbrella:" : @"☔",
                              @":koala:" : @"🐨",
                              @":fire:" : @"🔥",
                              @":tomato:" : @"🍅",
                              @":v:" : @"✌",
                              @":innocent:" : @"😇",
                              @":orange_book:" : @"📙",
                              @":u7a7a:" : @"🈳",
                              @":rose:" : @"🌹",
                              @":purse:" : @"👛",
                              @":smirk:" : @"😏",
                              @":triangular_flag_on_post:" : @"🚩",
                              @":ok_woman:" : @"🙆",
                              @":moyai:" : @"🗿",
                              @":arrow_up_down:" : @"↕",
                              @":scroll:" : @"📜",
                              @":thumbsdown:" : @"👎",
                              @":confounded:" : @"😖",
                              @":high_brightness:" : @"🔆",
                              @":rugby_football:" : @"🏉",
                              @":clock130:" : @"🕜",
                              @":sweat:" : @"😓",
                              @":station:" : @"🚉",
                              @":money_with_wings:" : @"💸",
                              @":see_no_evil:" : @"🙈",
                              @":scream:" : @"😱",
                              @":black_circle:" : @"⚫",
                              @":pear:" : @"🍐",
                              @":ledger:" : @"📒",
                              @":ocean:" : @"🌊",
                              @":crossed_flags:" : @"🎌",
                              @":grimacing:" : @"😬",
                              @":nut_and_bolt:" : @"🔩",
                              @":mask:" : @"😷",
                              @":bust_in_silhouette:" : @"👤",
                              @":baby_bottle:" : @"🍼",
                              @":cinema:" : @"🎦",
                              @":tangerine:" : @"🍊",
                              @":100:" : @"💯",
                              @":couple:" : @"👫",
                              @":underage:" : @"🔞",
                              @":bomb:" : @"💣",
                              @":clock530:" : @"🕠",
                              @":heart_decoration:" : @"💟",
                              @":police_car:" : @"🚓",
                              @":ant:" : @"🐜",
                              @":soccer:" : @"⚽",
                              @":birthday:" : @"🎂",
                              @":volcano:" : @"🌋",
                              @":space_invader:" : @"👾",
                              @":dancer:" : @"💃",
                              @":anguished:" : @"😧",
                              @":full_moon_with_face:" : @"🌝",
                              @":ghost:" : @"👻",
                              @":foggy:" : @"🌁",
                              @":arrow_up_small:" : @"🔼",
                              @":rocket:" : @"🚀",
                              @":round_pushpin:" : @"📍",
                              @":boom:" : @"💥",
                              @":trophy:" : @"🏆",
                              @":green_book:" : @"📗",
                              @":cold_sweat:" : @"😰",
                              @":clock930:" : @"🕤",
                              @":first_quarter_moon:" : @"🌓",
                              @":tram:" : @"🚊",
                              @":arrow_right:" : @"➡",
                              @":rooster:" : @"🐓",
                              @":speech_balloon:" : @"💬",
                              @":left_luggage:" : @"🛅",
                              @":lemon:" : @"🍋",
                              @":massage:" : @"💆",
                              @":cupid:" : @"💘",
                              @":radio:" : @"📻",
                              @":sake:" : @"🍶",
                              @":ramen:" : @"🍜",
                              @":(" : @"😞",
                              @":egg:" : @"🍳",
                              @":water_buffalo:" : @"🐃",
                              @":u5408:" : @"🈴",
                              @":lips:" : @"👄",
                              @":)" : @"😃",
                              @":rotating_light:" : @"🚨",
                              @":radio_button:" : @"🔘",
                              @":art:" : @"🎨",
                              @":golf:" : @"⛳",
                              @":loop:" : @"➿",
                              @":dog2:" : @"🐕",
                              @":fist:" : @"✊",
                              @":haircut:" : @"💇",
                              @":bird:" : @"🐦",
                              @":ox:" : @"🐂",
                              @":new_moon:" : @"🌑",
                              @":sweat_smile:" : @"😅",
                              @":bow:" : @"🙇",
                              @":beetle:" : @"🐞",
                              @":pushpin:" : @"📌",
                              @":signal_strength:" : @"📶",
                              @":bouquet:" : @"💐",
                              @":six_pointed_star:" : @"🔯",
                              @":ambulance:" : @"🚑",
                              @":shaved_ice:" : @"🍧",
                              @":grey_question:" : @"❔",
                              @":strawberry:" : @"🍓",
                              @":snowboarder:" : @"🏂",
                              @":necktie:" : @"👔",
                              @":woman:" : @"👩",
                              @":smile_cat:" : @"😸",
                              @":eight_spoked_asterisk:" : @"✳",
                              @":telephone_receiver:" : @"📞",
                              @":shell:" : @"🐚",
                              @":bulb:" : @"💡",
                              @":milky_way:" : @"🌌",
                              @":grinning:" : @"😀",
                              @":stuck_out_tongue_closed_eyes:" : @"😝",
                              @":hearts:" : @"♥",
                              @":arrow_upper_left:" : @"↖",
                              @":b:" : @"🅱",
                              @":icecream:" : @"🍦",
                              @":door:" : @"🚪",
                              @":rice:" : @"🍚",
                              @":e-mail:" : @"📧",
                              @":lollipop:" : @"🍭",
                              @":ring:" : @"💍",
                              @":baggage_claim:" : @"🛄",
                              @":heart_eyes_cat:" : @"😻",
                              @":vs:" : @"🆚",
                              @":melon:" : @"🍈",
                              @":rainbow:" : @"🌈",
                              @":tiger2:" : @"🐅",
                              @":ok:" : @"🆗",
                              @":hear_no_evil:" : @"🙉",
                              @":japanese_ogre:" : @"👹",
                              @":cat2:" : @"🐈",
                              @":busts_in_silhouette:" : @"👥",
                              @":anger:" : @"💢",
                              @":heavy_check_mark:" : @"✔",
                              @":poultry_leg:" : @"🍗",
                              @":bamboo:" : @"🎍",
                              @":waning_gibbous_moon:" : @"🌖",
                              @":link:" : @"🔗",
                              @":metro:" : @"🚇",
                              @":sun_with_face:" : @"🌞",
                              @":one:" : @"1⃣",
                              @":phone:" : @"☎",
                              @":yen:" : @"💴",
                              @":hocho:" : @"🔪",
                              @":free:" : @"🆓",
                              @":heavy_dollar_sign:" : @"💲",
                              @":hamster:" : @"🐹",
                              @":crystal_ball:" : @"🔮",
                              @":no_good:" : @"🙅",
                              @":ear:" : @"👂",
                              @":clock1:" : @"🕐",
                              @":gem:" : @"💎",
                              @":suspension_railway:" : @"🚟",
                              @":clock4:" : @"🕓",
                              @":clock7:" : @"🕖",
                              @":cool:" : @"🆒",
                              @":no_bicycles:" : @"🚳",
                              @":rice_cracker:" : @"🍘",
                              @":repeat:" : @"🔁",
                              @":railway_car:" : @"🚃",
                              @":doughnut:" : @"🍩",
                              @":rice_ball:" : @"🍙",
                              @":potable_water:" : @"🚰",
                              @":D" : @"😆",
                              @":speaker:" : @"🔊",
                              @":disappointed:" : @"😞",
                              @":gemini:" : @"♊",
                              @":non-potable_water:" : @"🚱",
                              @":large_blue_diamond:" : @"🔷",
                              @":arrow_up:" : @"⬆",
                              @":deciduous_tree:" : @"🌳",
                              @":violin:" : @"🎻",
                              @":satellite:" : @"📡",
                              @":house:" : @"🏠",
                              @":handbag:" : @"👜",
                              @":ballot_box_with_check:" : @"☑",
                              @":clock1030:" : @"🕥",
                              @":green_apple:" : @"🍏",
                              @":clubs:" : @"♣",
                              @":pouch:" : @"👝",
                              @":musical_keyboard:" : @"🎹",
                              @":kr:" : @"🇰🇷",
                              @":two_hearts:" : @"💕",
                              @":loudspeaker:" : @"📢",
                              @":waning_crescent_moon:" : @"🌘",
                              @":heavy_multiplication_x:" : @"✖",
                              @":put_litter_in_its_place:" : @"🚮",
                              @":stars:" : @"🌠",
                              @":sos:" : @"🆘",
                              @":joy:" : @"😂",
                              @":tennis:" : @"🎾",
                              @":jack_o_lantern:" : @"🎃",
                              @":apple:" : @"🍎",
                              @":camera:" : @"📷",
                              @":dromedary_camel:" : @"🐪",
                              @":heart:" : @"❤",
                              @":chart_with_upwards_trend:" : @"📈",
                              @":wedding:" : @"💒",
                              @":P" : @"😜",
                              @":no_entry_sign:" : @"🚫",
                              @":ram:" : @"🐏",
                              @":revolving_hearts:" : @"💞",
                              @":joy_cat:" : @"😹",
                              @":circus_tent:" : @"🎪",
                              @":abc:" : @"🔤",
                              @":musical_note:" : @"🎵",
                              @":pig:" : @"🐷",
                              @":barber:" : @"💈",
                              @":globe_with_meridians:" : @"🌐",
                              @":oncoming_taxi:" : @"🚖",
                              @":taurus:" : @"♉",
                              @":mountain_cableway:" : @"🚠",
                              @":goat:" : @"🐐",
                              @":seven:" : @"7⃣",
                              @":feet:" : @"👣",
                              @":zap:" : @"⚡",
                              @":dolls:" : @"🎎",
                              @":crocodile:" : @"🐊",
                              @":dvd:" : @"📀",
                              @":pig_nose:" : @"🐽",
                              @":vibration_mode:" : @"📳",
                              @":pray:" : @"🙏",
                              @":wc:" : @"🚾",
                              @":baseball:" : @"⚾",
                              @":blossum:" : @"🌼",
                              @":frowning:" : @"😦",
                              @":smile:" : @"😄",
                              @":syringe:" : @"💉",
                              @":ophiuchus:" : @"⛎",
                              @":four_leaf_clover:" : @"🍀",
                              @":black_joker:" : @"🃏",
                              @":neutral_face:" : @"😐",
                              @":unlock:" : @"🔓",
                              @":trident:" : @"🔱",
                              @":meat_on_bone:" : @"🍖",
                              @":candy:" : @"🍬",
                              @":ideograph_advantage:" : @"🉐",
                              @":leaves:" : @"🍃",
                              @":boat:" : @"⛵",
                              @":bangbang:" : @"‼",
                              @":clock11:" : @"🕚",
                              @":cocktail:" : @"🍸",
                              @":page_facing_up:" : @"📄",
                              @":vertical_traffic_light:" : @"🚦",
                              @":curry:" : @"🍛",
                              @":tada:" : @"🎉",
                              @":expressionless:" : @"😑",
                              @":clock230:" : @"🕝",
                              @":baby:" : @"👶",
                              @":u7533:" : @"🈸",
                              @":eight_pointed_black_star:" : @"✴",
                              @":man_with_turban:" : @"👳",
                              @":last_quarter_moon_with_face:" : @"🌜",
                              @":fries:" : @"🍟",
                              @":arrow_left:" : @"⬅",
                              @":mailbox_with_mail:" : @"📬",
                              @":mag:" : @"🔍",
                              @":soon:" : @"🔜",
                              @":thought_balloon:" : @"💭",
                              @":cry:" : @"😢",
                              @":saxophone:" : @"🎷",
                              @":snake:" : @"🐍",
                              @":crown:" : @"👑",
                              @":u6708:" : @"🈷",
                              @":mountain_bicyclist:" : @"🚵",
                              @":poop:" : @"💩",
                              @":person_with_pouting_face:" : @"🙎",
                              @":information_source:" : @"ℹ",
                              @":parking:" : @"🅿",
                              @":hatched_chick:" : @"🐥",
                              @":flashlight:" : @"🔦",
                              @":mailbox:" : @"📫",
                              @":restroom:" : @"🚻",
                              @":cancer:" : @"♋",
                              @":open_hands:" : @"👐",
                              @":+1:" : @"👍",
                              @":gun:" : @"🔫",
                              @":spaghetti:" : @"🍝",
                              @":herb:" : @"🌿",
                              @":clock630:" : @"🕡",
                              @":japan:" : @"🗾",
                              @":fishing_pole_and_fish:" : @"🎣",
                              @":runner:" : @"🏃",
                              @":satisfied:" : @"😌",
                              @":o" : @"😮",
                              @":leftwards_arrow_with_hook:" : @"↩",
                              @":purple_heart:" : @"💜",
                              @":mailbox_closed:" : @"📪",
                              @":point_down:" : @"👇",
                              @":congratulations:" : @"㊗",
                              @":grey_exclamation:" : @"❕",
                              @":bookmark:" : @"🔖",
                              @":christmas_tree:" : @"🎄",
                              @":womans_hat:" : @"👒",
                              @":part_alternation_mark:" : @"〽",
                              @":cd:" : @"💿",
                              @":exclamation:" : @"❗",
                              @":pensive:" : @"😔",
                              @":stuck_out_tongue:" : @"😛",
                              @":baby_symbol:" : @"🚼",
                              @":white_circle:" : @"⚪",
                              @":mens:" : @"🚹",
                              @":lock:" : @"🔒",
                              @":octopus:" : @"🐙",
                              @":pager:" : @"📟",
                              @":smiling_imp:" : @"😈",
                              @":ng:" : @"🆖",
                              @":diamond_shape_with_a_dot_inside:" : @"💠",
                              @":kimono:" : @"👘",
                              @":bell:" : @"🔔",
                              @":dizzy_face:" : @"😵",
                              @":sandal:" : @"👡",
                              @":elephant:" : @"🐘",
                              @":basketball:" : @"🏀",
                              @":credit_card:" : @"💳",
                              @":straight_ruler:" : @"📏",
                              @":camel:" : @"🐫",
                              @":hospital:" : @"🏥",
                              @":curly_loop:" : @"➰",
                              @":waxing_crescent_moon:" : @"🌒",
                              @":swimmer:" : @"🏊",
                              @":u5272:" : @"🈹",
                              @":u7981:" : @"🈲",
                              @":calling:" : @"📲",
                              @":busstop:" : @"🚏",
                              @":arrow_lower_right:" : @"↘",
                              @":japanese_castle:" : @"🏯",
                              @":capital_abcd:" : @"🔠",
                              @":star:" : @"⭐️",
                              @":last_quarter_moon:" : @"🌗",
                              @":id:" : @"🆔",
                              @":notes:" : @"🎶",
                              @":hotel:" : @"🏨",
                              @":abcd:" : @"🔡",
                              @":hamburger:" : @"🍔",
                              @":toilet:" : @"🚽",
                              @":ear_of_rice:" : @"🌾",
                              @":new:" : @"🆕",
                              @":key:" : @"🔑",
                              @":tired_face:" : @"😫",
                              @":closed_lock_with_key:" : @"🔐",
                              @":department_store:" : @"🏬",
                              @":arrow_right_hook:" : @"↪",
                              @":rewind:" : @"⏪",
                              @":mountain_railway:" : @"🚞",
                              @":fish_cake:" : @"🍥",
                              @":postbox:" : @"📮",
                              @":page_with_curl:" : @"📃",
                              @":cow2:" : @"🐄",
                              @":cake:" : @"🍰",
                              @":kiss:" : @"💋",
                              @":maple_leaf:" : @"🍁",
                              @":slot_machine:" : @"🎰",
                              @":ferris_wheel:" : @"🎡",
                              @":smiley:" : @"😃",
                              @":hushed:" : @"😯",
                              @":whale2:" : @"🐋"
                              };
        
//        key value逆转 来自https://github.com/valeriomazzeo/NSString-Emoji 直接转换好性能更好吧
        
//                NSMutableDictionary *unicodeDic = [NSMutableDictionary dictionary];
//                [unicodeToEmojiDic enumerateKeysAndObjectsUsingBlock:^(id key, id obj, BOOL *stop) {
//                    if ([obj isKindOfClass:[NSArray class]]) {
//                        for (NSString *object in obj) {
//                            [unicodeDic setObject:key forKey:object];
//                        }
//                    } else {
//                        [unicodeDic setObject:key forKey:obj];
//                    }
//                }];
//        unicodeAndEmojiDic = unicodeDic;
    }
}

#pragma mark - 遍历字符串把表情转unicode
- (NSString *)emojiToUnicode {
    if (!emojiAndUnicodeDic) {
        [NSString getEmojiAndStringDic];
    }
    
    if (self.length > 0) {
        __block NSMutableString *mString = [NSMutableString stringWithString:self];
        [emojiAndUnicodeDic enumerateKeysAndObjectsUsingBlock:^(id key, id obj, BOOL *stop) {
            NSString *string = ([obj isKindOfClass:[NSArray class]] ? [obj firstObject] : obj);
            [mString replaceOccurrencesOfString:key withString:string options:NSLiteralSearch range:NSMakeRange(0, mString.length)];
        }];
        return mString;
    }
    return self;
}

#pragma mark - 遍历字符串把unicode转表情
- (NSString *)unicodeToEmoji {
    if (!emojiAndUnicodeDic) {
        [NSString getEmojiAndStringDic];
    }
    
    if ([self rangeOfString:@":"].location != NSNotFound) {
        __block NSMutableString *mString = [NSMutableString stringWithString:self];
        [unicodeAndEmojiDic enumerateKeysAndObjectsUsingBlock:^(NSString *key, id obj, BOOL *stop) {
            [mString replaceOccurrencesOfString:key withString:obj options:NSLiteralSearch range:NSMakeRange(0, mString.length)];
        }];
        return mString;
    }
    return self;
}

@end
